[project]
name = "LORE_sa"
version = "0.0.1"
requires-python = ">=3.8"
description = "LOREM explainer package"
readme = "README.md"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["lore_sa"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

